// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Saiketsu.Service.Election.Infrastructure.Persistence;

#nullable disable

namespace Saiketsu.Service.Election.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230412123016_SampleMigration")]
    partial class SampleMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Saiketsu.Service.Election.Domain.Entities.CandidateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_candidate");

                    b.ToTable("candidate", (string)null);
                });

            modelBuilder.Entity("Saiketsu.Service.Election.Domain.Entities.ElectionCandidateEntity", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<int>("ElectionId")
                        .HasColumnType("integer")
                        .HasColumnName("election_id");

                    b.HasKey("CandidateId", "ElectionId")
                        .HasName("pk_election_candidate");

                    b.HasIndex("ElectionId")
                        .HasDatabaseName("ix_election_candidate_election_id");

                    b.ToTable("election_candidate", (string)null);
                });

            modelBuilder.Entity("Saiketsu.Service.Election.Domain.Entities.ElectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_election");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_election_owner_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_election_type_id");

                    b.ToTable("election", (string)null);
                });

            modelBuilder.Entity("Saiketsu.Service.Election.Domain.Entities.ElectionTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_election_type");

                    b.ToTable("election_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FirstPassThePost"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Saiketsu.Service.Election.Domain.Entities.ElectionUserEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("ElectionId")
                        .HasColumnType("integer")
                        .HasColumnName("election_id");

                    b.Property<bool>("Voted")
                        .HasColumnType("boolean")
                        .HasColumnName("voted");

                    b.HasKey("UserId", "ElectionId")
                        .HasName("pk_election_user");

                    b.HasIndex("ElectionId")
                        .HasDatabaseName("ix_election_user_election_id");

                    b.ToTable("election_user", (string)null);
                });

            modelBuilder.Entity("Saiketsu.Service.Election.Domain.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Saiketsu.Service.Election.Domain.Entities.ElectionCandidateEntity", b =>
                {
                    b.HasOne("Saiketsu.Service.Election.Domain.Entities.CandidateEntity", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_election_candidate_candidate_candidate_id");

                    b.HasOne("Saiketsu.Service.Election.Domain.Entities.ElectionEntity", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_election_candidate_elections_election_id");

                    b.Navigation("Candidate");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("Saiketsu.Service.Election.Domain.Entities.ElectionEntity", b =>
                {
                    b.HasOne("Saiketsu.Service.Election.Domain.Entities.UserEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_election_users_owner_id");

                    b.HasOne("Saiketsu.Service.Election.Domain.Entities.ElectionTypeEntity", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_election_election_type_entity_type_id");

                    b.Navigation("Owner");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Saiketsu.Service.Election.Domain.Entities.ElectionUserEntity", b =>
                {
                    b.HasOne("Saiketsu.Service.Election.Domain.Entities.ElectionEntity", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_election_user_election_election_id");

                    b.HasOne("Saiketsu.Service.Election.Domain.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_election_user_users_user_id");

                    b.Navigation("Election");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
